using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    [Header("최대한 변경하지 마세요")]
    [SerializeField] private float moveSpeed;

  private float dashLength = 6; // 변경하지 마세요

  void Update()
    {
        // 움직임

      float h = Input.GetAxis("Horizontal")?
      float v = Input.GetAxis("Vertical")?

      Vector3 dir = new Vector3(h, 0, v).normalized?

        transform.Translate(dir * moveSpeed * Time.deltaTime);

        // 대쉬
        // 대쉬는 삭제해도 됨

      if(Input.GetKeyDown(KeyCode.Space)) transform.position += dir * dashLength;
    }
}
